name: publish-bottles

on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-pull:
    if: github.event.label.name == 'pr-pull'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup git user
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          brew pr-pull \
            --debug \
            --tap=${{ github.repository }} \
            --workflows=tests.yml \
            --root-url="https://github.com/${{ github.repository }}/releases/download/why-$(brew ruby -e "puts Formula['why'].version")" \
            $PULL_REQUEST

      - name: Push bottle commit to main
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin "$BRANCH"